global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minut
# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:

      - targets: ['10.120.128.5:9177']
        labels:
          instance: compute-01

      - targets: ['10.120.128.6:9177']
        labels:
          instance: compute-02

      - targets: ['10.120.128.7:9177']
        labels:
          instance: compute-03
      
      - targets: ['10.120.128.8:9177']
        labels:
          instance: compute-04

      - targets: ['10.120.128.9:9177']
        labels:
          instance: compute-05

      - targets: ['10.120.128.10:9177']
        labels:
          instance: compute-06

      - targets: ['10.120.128.11:9177']
        labels:
          instance: compute-07

      - targets: ['10.120.128.12:9177']
        labels:
          instance: compute-08

      - targets: ['10.120.128.13:9177']
        labels:
          instance: compute-09

      - targets: ['10.120.128.14:9177']
        labels:
          instance: compute-010

      - targets: ['10.120.128.15:9177']
        labels:
          instance: compute-011

      - targets: ['10.120.128.16:9177']
        labels:
          instance: compute-012

      - targets: ['10.120.128.17:9177']
        labels:
          instance: compute-013

      - targets: ['10.120.128.18:9177']
        labels:
          instance: compute-014

      - targets: ['10.120.128.19:9177']
        labels:
          instance: compute-015

      - targets: ['10.120.128.21:9177']
        labels:
          instance: compute-016

      - targets: ['10.120.128.22:9177']
        labels:
          instance: compute-017

      - targets: ['10.120.128.23:9177']
        labels:
          instance: compute-018

      - targets: ['10.120.128.25:9177']
        labels:
          instance: compute-019

      - targets: ['10.120.128.26:9177']
        labels:
          instance: compute-020

      - targets: ['10.120.128.27:9177']
        labels:
          instance: compute-021

      - targets: ['10.120.128.29:9177']
        labels:
          instance: compute-022

      - targets: ['10.120.128.30:9177']
        labels:
          instance: compute-023

      - targets: ['10.120.128.31:9177']
        labels:
          instance: compute-024

      - targets: ['10.120.128.32:9177']
        labels:
          instance: compute-025

      - targets: ['10.120.128.33:9177']
        labels:
          instance: compute-026

      - targets: ['10.120.128.34:9177']
        labels:
          instance: compute-027

      - targets: ['10.120.128.35:9177']
        labels:
          instance: compute-028

      - targets: ['10.120.128.36:9177']
        labels:
          instance: compute-029

      - targets: ['10.120.128.37:9177']
        labels:
          instance: compute-030

      - targets: ['10.120.128.38:9177']
        labels:
          instance: compute-031

      - targets: ['10.120.128.39:9177']
        labels:
          instance: compute-032

      - targets: ['10.120.128.40:9177']
        labels:
          instance: compute-033

      - targets: ['10.120.128.41:9177']
        labels:
          instance: compute-034

      - targets: ['10.120.128.42:9177']
        labels:
          instance: compute-035
