{
 "title": "Monitor  Instance OpenStack",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance_id",
    "label": "instance_id",
    "query": {
     "query": "label_values(libvirt_domain_info_meta,uuid)"
    }
   },
   {
    "name": "instance_name",
    "label": "instance_name",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{uuid=\"$instance_id\"},instance_name)"
    }
   },
   {
    "name": "domain_name",
    "label": "domain_name",
    "query": {
     "query": "label_values(libvirt_domain_info_meta{uuid=\"$instance_id\"},domain)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance State",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "libvirt_domain_info_vstate{uuid=\"$instance_id\"}",
     "legendFormat": "{{instance_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_info_cpu_time_seconds_total{uuid=\"$instance_id\"}[10m])*100",
     "legendFormat": "%"
    },
    {}
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_used_percent{uuid=\"$instance_id\"}",
     "legendFormat": "%"
    }
   ]
  },
  {
   "title": "Read / Write Disk (bps)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "Bps", "label": "Read (-) / Write (+) (Bps)" }
   ],
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_write_bytes_total{uuid=\"$instance_id\"}[10m])",
     "legendFormat": "write - {{instance_name}}@{{target_device}}"
    },
    {
     "expr": "irate(libvirt_domain_block_stats_read_bytes_total{uuid=\"$instance_id\"}[10m])",
     "legendFormat": "read - {{instance_name}}@{{target_device}}"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "iops" }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_read_requests_total{uuid=\"$instance_id\"}[6m])",
     "legendFormat": "iops-read@{{target_device}}"
    },
    {
     "expr": "rate(libvirt_domain_block_stats_write_requests_total{uuid=\"$instance_id\"}[6m])",
     "legendFormat": "iops-write@{{target_device}}"
    }
   ]
  },
  {
   "title": "Network traffic receive",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bps", "label": "Average bandwidth " }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_receive_bytes_total{uuid=\"$instance_id\"}[10m])*8",
     "legendFormat": "RX-{{target_device}}"
    }
   ]
  },
  {
   "title": "Network traffic Transmit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bps", "label": "Average bandwidth " }
   ],
   "targets": [
    {
     "expr": "rate(libvirt_domain_interface_stats_transmit_bytes_total{uuid=\"$instance_id\"}[10m])*8",
     "legendFormat": "TX-{{target_device}}"
    }
   ]
  }
 ]
}