{
 "title": "Monitor VM On Compute",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "compute_node",
    "label": "compute_node",
    "query": {
     "query": "label_values(libvirt_domain_info_meta,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(libvirt_domain_info_cpu_time_seconds_total{instance=\"$compute_node\"}[10m])*100"
    }
   ]
  },
  {
   "title": "CPU Current",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "group": { "filter": "OPS-SERVER" },
     "host": { "filter": "$compute_node" },
     "item": { "filter": "CPU utilization" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "RAM",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "libvirt_domain_memory_stats_used_percent{instance=\"$compute_node\"}"
    }
   ]
  },
  {
   "title": "RAM Current",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "group": { "filter": "OPS-SERVER" },
     "host": { "filter": "$compute_node" },
     "item": { "filter": "Memory utilization" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Disk Write/Read",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "irate(libvirt_domain_block_stats_write_bytes_total{instance=\"$compute_node\"}[10m])"
    },
    {
     "expr": "irate(libvirt_domain_block_stats_read_bytes_total{instance=\"$compute_node\"}[10m])"
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 10 },
   "targets": [
    {
     "expr": "rate(libvirt_domain_block_stats_read_requests_total{instance=\"$compute_node\"}[6m])"
    },
    {
     "expr": "rate(libvirt_domain_block_stats_write_requests_total{instance=\"$compute_node\"}[6m])"
    }
   ]
  },
  {
   "title": "Network Traffic Receive",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 3, "y": 20 },
   "targets": [
    {
     "expr": "irate(libvirt_domain_interface_stats_receive_bytes_total{instance=\"$compute_node\"}[10m])*8"
    },
    {
     "expr": "irate(libvirt_domain_interface_stats_transmit_bytes_total{instance=\"$compute_node\"}[10m])*8"
    }
   ]
  }
 ]
}